algoritmo "condicionalidade"
// Função :
// Autor : Esther oliveira costa
// Data : 12/06/2020
// Seção de Declarações 
var
idade: inteiro
resp: caracter

inicio
// Seção de Comandos 

escreval (" qual sua idade: ")
leia(idade)

escreval (" possui habilitação : ")
leia (resp)

//decisão

se (( idade>=18) e ( resp="sim" )) entao
    escreval (" pode passar: ")

senao
      escreval (" não pode passar: ")
      
fimse



fimalgoritmo
